// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Infrastructure.Persistence;

#nullable disable

namespace OnlineShop.Infrastructure.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Core i7, 16GB RAM, 512GB SSD",
                            DiscountPercent = 10m,
                            Name = "Laptop 14\"",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "128GB, OLED",
                            DiscountPercent = 5m,
                            Name = "Smartphone Pro",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Noise Cancelling",
                            DiscountPercent = 30m,
                            Name = "Headphones",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ergonomic",
                            DiscountPercent = 2m,
                            Name = "Wireless Mouse",
                            Price = 600m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
